# Generated by Django 5.0.6 on 2024-06-16 08:07

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone', models.IntegerField()),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('rate', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='places/')),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('location_type', models.CharField(choices=[('Rs', 'Restaurant'), ('Pr', 'Park'), ('Zo', 'Zoo'), ('Mu', 'Museum'), ('Am', 'Amusement Park'), ('Ma', 'Mall')], max_length=3)),
            ],
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(check=models.Q(('rate__lte', 5)), name='rate_lte_5'),
        ),
    ]
