# Generated by Django 5.0.6 on 2024-07-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location_type',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Park', 'Park'), ('Zoo', 'Zoo'), ('Museum', 'Museum'), ('Amusement Park', 'Amusement Park'), ('Mall', 'Mall'), ('Tower', 'Tower'), ('Historical', 'Historical'), ('Other', 'Other')], max_length=14),
        ),
    ]
