# Generated by Django 5.0.6 on 2024-06-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_place_place_rate_lte_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location_type',
            field=models.CharField(choices=[('Rs', 'Restaurant'), ('Pr', 'Park'), ('Zo', 'Zoo'), ('Mu', 'Museum'), ('Am', 'Amusement Park'), ('Ma', 'Mall'), ('Ot', 'Other')], max_length=3),
        ),
    ]
