# Generated by Django 5.0.6 on 2024-06-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_contact_email_remove_contact_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(default='default message for models'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='default name', max_length=250),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='default message for models'),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='default name', max_length=250),
        ),
    ]
