# Generated by Django 5.0.6 on 2024-06-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment_created_time_comment_email_comment_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location_type',
            field=models.CharField(choices=[('Rs', 'Restaurant'), ('Pr', 'Park'), ('Zo', 'Zoo'), ('Mu', 'Museum'), ('Am', 'Amusement Park'), ('Ma', 'Mall'), ('Tw', 'Tower'), ('Hi', 'Historical'), ('Ot', 'Other')], max_length=3),
        ),
    ]
